spring:
 datasource:
   url: jdbc:mysql://localhost:3306/customerDB?createDatabaseIfNotExist=true
   username: root
   password: root
   driver-class-name: com.mysql.jdbc.Driver

 jpa:
   properties:
     hibernate:
       dialect=org.hibernate.dialect.MySQL5Dialect
       show-sql=true
       ddl-auto=update
     naming:
       physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

 autoconfigure:
   exclude:org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


