
server:
  port: 8080

spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/customerdb
    username: postgres
    password: damith
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

